### ISSUE TITLE
No an issue

### ISSUE THREAD

**Issue by chandanroksjsr** [LasVegasCoder/Anti-DDOS-Script#4]
Can i Use it for Fivem Servers? and sorry to sound stupid

**Comment by alekitopi** [comment]
Yes, you can use it for everything but keep warning with the ports.

**Comment by LasVegasCoder** [comment]
@chandanroksjsr Yes, the script runs on any systems that has iptables installed. 
Before you run the script check if you have iptables installed using the following command from console:

root@WebServer:~# iptables --version
iptables v1.6.0

This server currently has iptables version v1.6.0 installed, your version may not be the same as this one above, what's important is that you have iptables installed, since most firewall softwares and  routers uses iptables to secure systems, why not use a script to constructively create rules that ALLOW access, DENY access, BAN violators, UNBAN violators, SET triggers, LOG triggers and more, 

Now that you're feeling the "what does it like to have full security under my control instead of clicking on buttons to run codes that I don't see or know for me under the hood."  let's proceed to run the script.

If you do have iptables installed, it's a good ethics to always back up your old iptables rules before creating new rules.

Please follow the instructions to run it successfully.
